# .streamlit/config.toml
[theme]
base = "dark"
# Primary accent color.
primaryColor = "green"

# Background color of the app.
backgroundColor = "#515151"

# Background color used for most interactive widgets.
# secondaryBackgroundColor = ""

# Color used for almost all text.
textColor = "#f8f6f0"